name: Release

on:
  push:
    branches:
      - release/**
      - release
      
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install Pnpm
        run: npm install -g pnpm

      - name: Install Dependencies
        run: pnpm i --no-frozen-lockfile

      - name: Build
        run: pnpm build:ci

      - name: Check Build
        run: cat ./packages/mele-cli/package.json

      - name: Secrets To Env Var
        run: |
          echo "NPM_TOKEN=${{ secrets.NPM_TOKEN }}" >> "$GITHUB_ENV"

      - name: Authenticate with npm registry
        run: pnpm config set //registry.npmjs.org/:_authToken=${NPM_TOKEN}

      - name: Config npm
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" >> .npmrc
      
      - name: Publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: pnpm release

